### ISSUE TITLE
Can your robot monitor multiple keywords at the same time?

### ISSUE THREAD

**Issue by szsyzx** [Steeven9/ScheduleTweetBot#1]
Can your robot monitor multiple keywords at the same time?

**Comment by Steeven9** [comment]
Yes, in the configuration files you can specify the `schedule_keywords` array, as in this [example](https://github.com/Steeven9/ScheduleTweetBot/blob/0be99bc6f09a907ee18bcb7d5a3cd737c97f3107/data_kfp.py#L8). I will update the documentation soon to describe it better.
